// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoyqrosxiorebjckyujk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpveXFyb3N4aW9yZWJqY2t5dWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTA3OTUsImV4cCI6MjA3Mzg4Njc5NX0.E_bd8mteQKPlRubdTXKJptP4y0cp4JqqxHWSKkS5u8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});